spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/chargingpile?tinyInt1isBit=false&useSSL=true
      username: root
      password: lqc13890
mybatis:
   mapperLocations: classpath:/mapper/*.xml,classpath:/mapper/*/*.xml
   configuration:
      mapUnderscoreToCamelCase: true
server:
  port: 8989

